(rule
 (target
  (dir dist))
 (action
  (progn
   (bash
    "mkdir -p dist/{lib/blibli,var/{{log,data,www}/blibli,www/blibli/css,run}}")
   (bash "cp %{dep:src/client/blibli.bc.js} dist/var/www/blibli/blibli.js")
   (bash
    "cp %{dep:static/css/blibli.css} dist/var/www/blibli/css/blibli.css"))))

