;
; This Dune file was generated with ocsigen-dune-rules.
; To update it, modify the invocation below and run
;
;     dune runtest --auto-promote
;

(rule
 (with-stdout-to
  dune.corrected
  (run
   ocsigen-dune-rules
   gen-application
   blibli
   --server-libraries
   ocsipersist-sqlite,ocsigenserver.ext.staticmod,ocsigenserver.ext.cors,ocsigenserver.ext.accesscontrol,ocsigenserver.ext.deflatemod
   --eliom-libraries
   blibli.lib,blibli.services)))

;
; Below this line, any changes will be overwritten.
;

(rule
 (alias runtest)
 (action
  (diff dune dune.corrected)))

(executable
 (public_name blibli)
 (name blibli)
 (package blibli)
 (modes byte native)
 (preprocess
  (pps eliom.ppx.server ocsigen-ppx-rpc --rpc-raw))
 (libraries
  eliom.server
  ocsigenserver
  js_of_ocaml
  ocsipersist-sqlite
  ocsigenserver.ext.staticmod
  ocsigenserver.ext.cors
  ocsigenserver.ext.accesscontrol
  ocsigenserver.ext.deflatemod
  blibli.lib.server
  blibli.services.server))

(subdir
 client
 (executable
  (name blibli)
  (modes js byte)
  (preprocess
   (pps js_of_ocaml-ppx))
  (js_of_ocaml
   (build_runtime_flags :standard --enable use-js-string)
   (flags :standard --enable with-js-error --enable use-js-string))
  (libraries
   eliom.client
   js_of_ocaml
   js_of_ocaml-lwt
   blibli.lib.client
   blibli.services.client))
 (dynamic_include ../dune.client))

(rule
 (deps
  (glob_files *.eliom)
  (glob_files *.eliomi))
 (action
  (with-stdout-to
   dune.client
   (run ocsigen-dune-rules gen-client-modules .))))

(rule
 (alias runtest)
 (action
  (run
   ocsigen-dune-rules
   check-modules
   --client
   %{dep:client/blibli.bc}
   --server
   %{dep:blibli.bc})))
